// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitBetMaticFunctions.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20240823182909_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IndicatorThresholds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AdxPeriod")
                        .HasColumnType("int");

                    b.Property<double>("AdxStrongTrend")
                        .HasColumnType("float");

                    b.Property<decimal>("AtrMultiplier")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AtrPeriod")
                        .HasColumnType("int");

                    b.Property<double>("BollingerBandsDeviation")
                        .HasColumnType("float");

                    b.Property<int>("BollingerBandsPeriod")
                        .HasColumnType("int");

                    b.Property<int>("BuyThreshold")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MacdFastPeriod")
                        .HasColumnType("int");

                    b.Property<decimal>("MacdSignalLine")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MacdSignalPeriod")
                        .HasColumnType("int");

                    b.Property<int>("MacdSlowPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("ParabolicSarMax")
                        .HasColumnType("float");

                    b.Property<double>("ParabolicSarStep")
                        .HasColumnType("float");

                    b.Property<int>("RocPeriod")
                        .HasColumnType("int");

                    b.Property<int>("RsiOverbought")
                        .HasColumnType("int");

                    b.Property<int>("RsiOversold")
                        .HasColumnType("int");

                    b.Property<int>("RsiPeriod")
                        .HasColumnType("int");

                    b.Property<int>("SellThreshold")
                        .HasColumnType("int");

                    b.Property<int>("SmaLongTerm")
                        .HasColumnType("int");

                    b.Property<int>("SmaShortTerm")
                        .HasColumnType("int");

                    b.Property<double?>("StochasticOverbought")
                        .HasColumnType("float");

                    b.Property<double?>("StochasticOversold")
                        .HasColumnType("float");

                    b.Property<int>("StochasticPeriod")
                        .HasColumnType("int");

                    b.Property<int>("StochasticSignalPeriod")
                        .HasColumnType("int");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Strategy", "Market", "CreatedAt");

                    b.ToTable("IndicatorThresholds");
                });
#pragma warning restore 612, 618
        }
    }
}
